Index mixin and add test
nguyenquangminh0711/ruby_zen pull request #4
Opened 2018-08-08 13:47 UTC by Khoahaha

# Summary
- Index module mixin

# Changes
- Register new processors: `include`, `extend` and `prepend`
- Add three new containers to hold different types of mixin-ed modules and their according index functions
- Add test

2018-08-08 16:12 UTC, nguyenquangminh0711 commented on spec/definitions/mixin_spec.rb
> +        include UpOnTheSky
This test is simple. Let's add some more tests that includes multiple prepends and includes; as well as normal methods to test out the behaviors.

2018-08-14 17:45 UTC, 0x2c7 requested changes
IMO, the ClassObject should be simple. It is the data storage and method searcher. The logic related to "re-define" guessing constant type should belong to higher level, in this case, Engine. The `define_class` should be responsible for this job.

```ruby
def define_class(class_name)
  class_name = class_name.to_s
  return @classes[class_name] if !block_given?

  class_object = yield
  if @classes[class_name]
    # Finalize class object type
    @classes[class_name].tap do |old_object|
       old_object.is_module = class_object.is_module
       old_object.namespace = class_object.namespace
       old_object.superclass = class_object.superclass
   end
  else
    @classes[class_name] = class_object
  end
end
```

By doing this, we don't need to pollute the ClassObject with `is_defined`.

2018-08-14 17:45 UTC, nguyenquangminh0711 commented on lib/ruby_zen/class_object.rb
> +    def available_instance_methods
Why don't we just replace `instance_method_objects` by this implementation?

2018-08-16 14:49 UTC, nguyenquangminh0711 commented on lib/ruby_zen/indexers/iseq_indexer.rb
> +            RubyZen::ClassObject.new(name)
Thanks to the class definition update, we can now be sure about the class type (module or normal class). So, I think we still need to assume that an unknown class is a module, until we have better evidence, like what Ruby is doing.

2018-08-19 17:02 UTC, luong-komorebi approved these changes
em thấy ok

2018-08-19 17:03 UTC, 0x2c7 approved these changes
LGTM 👍

2018-08-19 17:03 UTC, merged

2018-08-19 17:22 UTC, luong-komorebi commented
@Khoahaha mốt anh làm chung trên repo này, đừng fork ra mỗi lần xem code checkout đồ khó khăn